name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install west
          sudo apt update
          sudo apt install -y ninja-build cmake gcc gperf ccache python3-pip

      - name: Initialize west
        run: |
          west init workspace
          cd workspace
          west update

      - name: Copy project into workspace
        run: |
          cp -r * workspace/

      - name: Build unit test
        run: |
          cd workspace
          west build -b native_sim tests/unit/ringbuf --build-dir build_test

      - name: Run test
        run: |
          cd workspace/build_test
          ninja run